/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import dao.KhachHangDAO;
import dao.TaiKhoanDAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.KhachHang;
import model.TaiKhoan;

public class AddKhachHang extends javax.swing.JDialog {

    /**
     * Creates new form AddAccount
     */
    private QuanLiKhachHangForm parent;

    public AddKhachHang(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.parent = (QuanLiKhachHangForm) parent;
        initComponents();
        setLocationRelativeTo(null);
         txtMaKH.setText(createIdPC());

    }

   

    private AddKhachHang(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ThemKH = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtsodienthoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChiKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcmtKH = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxgioitinh = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm tài khoản mới");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel2.setText("Mã khách hàng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, -1));

        txtMaKH.setEditable(false);
        txtMaKH.setFont(new java.awt.Font("SF Pro Display", 0, 16));
        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 298, 38));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel3.setText("Tên khách hàng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 24));

        txtTenKH.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 298, 38));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel4.setText("Ngày sinh");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, 20));

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel5.setText("Giới tính");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 70, 20));

        ThemKH.setBackground(new java.awt.Color(153, 0, 51));
        ThemKH.setForeground(new java.awt.Color(255, 255, 255));
        ThemKH.setText("Thêm");
        ThemKH.setBorder(null);
        ThemKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemKHActionPerformed(evt);
            }
        });
        jPanel1.add(ThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 140, 38));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Huỷ");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 140, 38));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÊM KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        txtsodienthoai.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtsodienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 298, 38));

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel6.setText("Địa chỉ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, -1));

        txtDiaChiKH.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtDiaChiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 298, 38));

        jLabel7.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel7.setText("CCCD/CMND");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, -1));

        txtcmtKH.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtcmtKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 298, 38));

        txtngaysinh.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 298, 38));

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel8.setText("Số điện thoại");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, -1));

        cbxgioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbxgioitinh.setPreferredSize(new java.awt.Dimension(200, 30));
        cbxgioitinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxgioitinhItemStateChanged(evt);
            }
        });
        cbxgioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxgioitinhActionPerformed(evt);
            }
        });
        cbxgioitinh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxgioitinhPropertyChange(evt);
            }
        });
        jPanel1.add(cbxgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemKHActionPerformed
        // TODO add your handling code here:
        try {
            String maKh = txtMaKH.getText().trim();
            String tenKh = txtTenKH.getText().trim();
            String sdtKh = txtsodienthoai.getText().trim(); 
            String cmtKH = txtcmtKH.getText().trim();
            String ngaySinhKH = txtngaysinh.getText().trim();
                String diachiKh = txtDiaChiKH.getText().trim();
          boolean gioiTinhKH = (cbxgioitinh.getSelectedIndex() == 1);

            if (maKh.equals("") || tenKh.equals("") || sdtKh.equals("") || diachiKh.equals("") || cmtKH.equals("") ) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            } else {
                KhachHang kh = new KhachHang();
                kh.setMaKhachHang(maKh);
                kh.setTenKhachHang(tenKh);
                kh.setSoDienThoai(sdtKh);
                kh.setDiaChi(diachiKh);  
                kh.setNgaySinh(ngaySinhKH);
                kh.setChungMinhThu(cmtKH);
       
                // Xác định giới tính dựa trên giá trị nhập vào
               
                kh.setGioiTinh(gioiTinhKH);

                KhachHangDAO.getInstance().insert(kh);
                JOptionPane.showMessageDialog(this, "Thêm thành công !");
                parent.loadDataToTable(KhachHangDAO.getInstance().selectAll());
                this.dispose();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giới tính là số (0 hoặc 1) !", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            System.out.println("view.AddKhachHang.ThemKHActionPerformed()");
            JOptionPane.showMessageDialog(this, "Thêm không thành công !", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ThemKHActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void cbxgioitinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxgioitinhItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxgioitinhItemStateChanged

    private void cbxgioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxgioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxgioitinhActionPerformed

    private void cbxgioitinhPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxgioitinhPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxgioitinhPropertyChange
public String createIdPC() {
        ArrayList<KhachHang> mtAll = KhachHangDAO.getInstance().selectAll();

        int i = 1;
        while (true) {
            boolean exists = false;
            for (KhachHang khachhang : mtAll) {
                if (khachhang.getMaKhachHang().equals("KH" + i)) {
                    exists = true;
                    break;
                }
            }
            if (!exists) {
                break;
            } else {
                i++;
            }
        }

        return "KH" + i;

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatLightLaf());
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddKhachHang dialog = new AddKhachHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThemKH;
    private javax.swing.JComboBox<String> cbxgioitinh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtcmtKH;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsodienthoai;
    // End of variables declaration//GEN-END:variables
}
