/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.TaiKhoan;

public class QuanLi extends javax.swing.JFrame {

    Color DefaultColor, ClickedColor;

    public QuanLi() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private TaiKhoan currentAcc;

    public TaiKhoan getCurrentAcc() {
        return currentAcc;
    }

    public QuanLi(TaiKhoan t) throws UnsupportedLookAndFeelException {
        ImageIcon logo = new ImageIcon(getClass().getResource("/icon/logo.png"));
        setIconImage(logo.getImage());
        UIManager.setLookAndFeel(new FlatLightLaf());
        UIManager.put("Table.showVerticalLines", true);
        UIManager.put("Table.showHorizontalLines", true);
        initComponents();
        setLocationRelativeTo(null);
        this.currentAcc = t;
        QuanLiPhongForm pf = new QuanLiPhongForm();
        MainContent.add(pf).setVisible(true);
//        pf.checkRole(currentAcc);

        DefaultColor = new Color(153,0,51);
        ClickedColor = new Color(102,0,0);
       
       
        
        
        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(ClickedColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
  setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavbarMenu = new javax.swing.JPanel();
        QuanLiPhong = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        KhachHang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NameUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HoaDonDichVu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TonKho = new javax.swing.JPanel();
        KhoDichVu = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DoiThongTin = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        QuanLiDichVu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        HoaDonPhong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lí khách sạn");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NavbarMenu.setBackground(new java.awt.Color(153, 0, 51));
        NavbarMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        NavbarMenu.setPreferredSize(new java.awt.Dimension(240, 850));
        NavbarMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QuanLiPhong.setBackground(new java.awt.Color(51, 51, 51));
        QuanLiPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLiPhong.setPreferredSize(new java.awt.Dimension(240, 30));
        QuanLiPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLiPhongMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLiPhongMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/extra-bed.png"))); // NOI18N
        jLabel2.setText("QUẢN LÍ  PHÒNG");

        javax.swing.GroupLayout QuanLiPhongLayout = new javax.swing.GroupLayout(QuanLiPhong);
        QuanLiPhong.setLayout(QuanLiPhongLayout);
        QuanLiPhongLayout.setHorizontalGroup(
            QuanLiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        QuanLiPhongLayout.setVerticalGroup(
            QuanLiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLiPhongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        NavbarMenu.add(QuanLiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        DangXuat.setBackground(new java.awt.Color(222, 14, 66));
        DangXuat.setPreferredSize(new java.awt.Dimension(240, 30));
        DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangXuatMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (2).png"))); // NOI18N
        jLabel5.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NavbarMenu.add(DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 240, -1));

        KhachHang.setBackground(new java.awt.Color(222, 14, 66));
        KhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachHang.setPreferredSize(new java.awt.Dimension(240, 30));
        KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhachHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KhachHangMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N
        jLabel6.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout KhachHangLayout = new javax.swing.GroupLayout(KhachHang);
        KhachHang.setLayout(KhachHangLayout);
        KhachHangLayout.setHorizontalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        KhachHangLayout.setVerticalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KhachHangLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        NavbarMenu.add(KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, 30));

        NameUser.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser.setForeground(new java.awt.Color(255, 255, 255));
        NameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser.setText("ADMIN");
        NameUser.setToolTipText("");
        NavbarMenu.add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, -1));

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HI !");
        NavbarMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 40, -1));

        HoaDonDichVu.setBackground(new java.awt.Color(222, 14, 66));
        HoaDonDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoaDonDichVu.setPreferredSize(new java.awt.Dimension(240, 30));
        HoaDonDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonDichVuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDonDichVuMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/electricity-bill.png"))); // NOI18N
        jLabel9.setText("HÓA ĐƠN DỊCH VỤ");

        javax.swing.GroupLayout HoaDonDichVuLayout = new javax.swing.GroupLayout(HoaDonDichVu);
        HoaDonDichVu.setLayout(HoaDonDichVuLayout);
        HoaDonDichVuLayout.setHorizontalGroup(
            HoaDonDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        HoaDonDichVuLayout.setVerticalGroup(
            HoaDonDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HoaDonDichVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        NavbarMenu.add(HoaDonDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        TonKho.setBackground(new java.awt.Color(222, 14, 66));
        TonKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TonKhoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TonKhoMousePressed(evt);
            }
        });

        KhoDichVu.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        KhoDichVu.setForeground(new java.awt.Color(255, 255, 255));
        KhoDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/warehouse.png"))); // NOI18N
        KhoDichVu.setText("KHO DỊCH VỤ");
        KhoDichVu.setPreferredSize(new java.awt.Dimension(240, 30));

        javax.swing.GroupLayout TonKhoLayout = new javax.swing.GroupLayout(TonKho);
        TonKho.setLayout(TonKhoLayout);
        TonKhoLayout.setHorizontalGroup(
            TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TonKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhoDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        TonKhoLayout.setVerticalGroup(
            TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TonKhoLayout.createSequentialGroup()
                .addComponent(KhoDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        NavbarMenu.add(TonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 30));

        ThongKe.setBackground(new java.awt.Color(222, 14, 66));
        ThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongKeMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2.png"))); // NOI18N
        jLabel13.setText("THỐNG KÊ");

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongKeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        NavbarMenu.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        DoiThongTin.setBackground(new java.awt.Color(222, 14, 66));
        DoiThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoiThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoiThongTinMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DoiThongTinMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/letter-i.png"))); // NOI18N
        jLabel14.setText("ĐỔI THÔNG TIN");

        javax.swing.GroupLayout DoiThongTinLayout = new javax.swing.GroupLayout(DoiThongTin);
        DoiThongTin.setLayout(DoiThongTinLayout);
        DoiThongTinLayout.setHorizontalGroup(
            DoiThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        DoiThongTinLayout.setVerticalGroup(
            DoiThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoiThongTinLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        NavbarMenu.add(DoiThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 240, 30));

        TaiKhoan.setBackground(new java.awt.Color(222, 14, 66));
        TaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaiKhoan.setPreferredSize(new java.awt.Dimension(240, 30));
        TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaiKhoanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaiKhoanMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/teamwork.png"))); // NOI18N
        jLabel12.setText("TÀI KHOẢN");

        javax.swing.GroupLayout TaiKhoanLayout = new javax.swing.GroupLayout(TaiKhoan);
        TaiKhoan.setLayout(TaiKhoanLayout);
        TaiKhoanLayout.setHorizontalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TaiKhoanLayout.setVerticalGroup(
            TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaiKhoanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        NavbarMenu.add(TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        QuanLiDichVu.setBackground(new java.awt.Color(222, 14, 66));
        QuanLiDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLiDichVu.setPreferredSize(new java.awt.Dimension(240, 30));
        QuanLiDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanLiDichVuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLiDichVuMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sale.png"))); // NOI18N
        jLabel4.setText("QUẢN LÍ DỊCH VỤ");

        javax.swing.GroupLayout QuanLiDichVuLayout = new javax.swing.GroupLayout(QuanLiDichVu);
        QuanLiDichVu.setLayout(QuanLiDichVuLayout);
        QuanLiDichVuLayout.setHorizontalGroup(
            QuanLiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLiDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        QuanLiDichVuLayout.setVerticalGroup(
            QuanLiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLiDichVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        NavbarMenu.add(QuanLiDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        HoaDonPhong.setBackground(new java.awt.Color(102, 0, 0));
        HoaDonPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoaDonPhong.setPreferredSize(new java.awt.Dimension(240, 30));
        HoaDonPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonPhongMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDonPhongMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/receipt.png"))); // NOI18N
        jLabel3.setText("HÓA ĐƠN PHÒNG");

        javax.swing.GroupLayout HoaDonPhongLayout = new javax.swing.GroupLayout(HoaDonPhong);
        HoaDonPhong.setLayout(HoaDonPhongLayout);
        HoaDonPhongLayout.setHorizontalGroup(
            HoaDonPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        HoaDonPhongLayout.setVerticalGroup(
            HoaDonPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        NavbarMenu.add(HoaDonPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        getContentPane().add(NavbarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 870));

        MainContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        getContentPane().add(MainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1300, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMousePressed
        // TODO add your handling code here:

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(ClickedColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_KhachHangMousePressed

    private void QuanLiPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiPhongMousePressed
        // TODO add your handling code here:

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(ClickedColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_QuanLiPhongMousePressed

    private void HoaDonPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonPhongMousePressed
        // TODO add your handling code here:

        HoaDonPhong.setBackground(ClickedColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_HoaDonPhongMousePressed

    private void QuanLiDichVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiDichVuMousePressed
        // TODO add your handling code here:

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(ClickedColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_QuanLiDichVuMousePressed


    private void HoaDonDichVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonDichVuMousePressed
        // TODO add your handling code here:

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(ClickedColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_HoaDonDichVuMousePressed

    private void TonKhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TonKhoMousePressed
        // TODO add your handling code here:

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(ClickedColor);
        TaiKhoan.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_TonKhoMousePressed

    private void DangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DangXuatMousePressed

    private void KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMouseClicked
        // TODO add your handling code here:
        QuanLiKhachHangForm af = new QuanLiKhachHangForm();
        MainContent.removeAll();
        MainContent.add(af).setVisible(true);
    }//GEN-LAST:event_KhachHangMouseClicked

    private void TonKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TonKhoMouseClicked
        // TODO add your handling code here:
        QuanLiKhoDichVu px = new QuanLiKhoDichVu();
        MainContent.removeAll();
        MainContent.add(px).setVisible(true);


    }//GEN-LAST:event_TonKhoMouseClicked

    private void QuanLiPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiPhongMouseClicked
        // TODO add your handling code here:
        QuanLiPhongForm nhaphang = new QuanLiPhongForm();
        nhaphang.setNguoiNhapHang(this.currentAcc.getTaiKhoan());

        MainContent.removeAll();
        MainContent.add(nhaphang).setVisible(true);
    }//GEN-LAST:event_QuanLiPhongMouseClicked

    private void HoaDonPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonPhongMouseClicked
        // TODO add your handling code here:
        HoaDonPhongForm pn = new HoaDonPhongForm(this.getCurrentAcc());
        MainContent.removeAll();
        MainContent.add(pn).setVisible(true);
    }//GEN-LAST:event_HoaDonPhongMouseClicked

    private void QuanLiDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiDichVuMouseClicked
        // TODO add your handling code here:
        QuanLiDichVuForm xh = new QuanLiDichVuForm();
        xh.setNguoiTao(this.currentAcc.getTenNV());
        MainContent.removeAll();
        MainContent.add(xh).setVisible(true);
    }//GEN-LAST:event_QuanLiDichVuMouseClicked

    private void HoaDonDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonDichVuMouseClicked
        // TODO add your handling code here:
        HoaDonDichVuForm px = new HoaDonDichVuForm(this.getCurrentAcc());
        MainContent.removeAll();
        MainContent.add(px).setVisible(true);
    }//GEN-LAST:event_HoaDonDichVuMouseClicked

    private void DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMouseClicked
        // TODO add your handling code here:
        int relly = JOptionPane.showConfirmDialog(
                null,
                "Bạn muốn thoát khỏi chương trình ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (relly == JOptionPane.YES_OPTION) {
            this.dispose();
            DangNhap a = new DangNhap();
            a.setVisible(true);
        } else {
            DangXuat.setBackground(DefaultColor);
        }
    }//GEN-LAST:event_DangXuatMouseClicked

    private void TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMouseClicked
        // TODO add your handling code here:
        QuanLiTaiKhoan ac = new QuanLiTaiKhoan();
        MainContent.removeAll();
        MainContent.add(ac).setVisible(true);
    }//GEN-LAST:event_TaiKhoanMouseClicked

    private void TaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMousePressed
        // TODO add your handling code here:

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(ClickedColor);
        ThongKe.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_TaiKhoanMousePressed

    private void ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseClicked
        // TODO add your handling code here:
        QuanLiThongKe tk = new QuanLiThongKe();
        MainContent.removeAll();
        MainContent.add(tk).setVisible(true);
    }//GEN-LAST:event_ThongKeMouseClicked

    private void ThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMousePressed
        // TODO add your handling code here:
        ThongKe.setBackground(ClickedColor);

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        DoiThongTin.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);

    }//GEN-LAST:event_ThongKeMousePressed

    private void DoiThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoiThongTinMouseClicked
        // TODO add your handling code here:
        UpdateMatKhau cp = new UpdateMatKhau(this, rootPaneCheckingEnabled, getCurrentAcc());
        cp.setVisible(true);
    }//GEN-LAST:event_DoiThongTinMouseClicked

    private void DoiThongTinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoiThongTinMousePressed
      ThongKe.setBackground(DefaultColor);

        HoaDonPhong.setBackground(DefaultColor);
        QuanLiPhong.setBackground(DefaultColor);
        QuanLiDichVu.setBackground(DefaultColor);
        HoaDonDichVu.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan.setBackground(DefaultColor);
        DoiThongTin.setBackground(ClickedColor);
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_DoiThongTinMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát ?", "Exit?", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QuanLi().setVisible(true);
            }
        });
        
        
    }

    public void setName(String name) {
        this.NameUser.setText(name);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel DoiThongTin;
    private javax.swing.JPanel HoaDonDichVu;
    private javax.swing.JPanel HoaDonPhong;
    private javax.swing.JPanel KhachHang;
    private javax.swing.JLabel KhoDichVu;
    private javax.swing.JPanel MainContent;
    private javax.swing.JLabel NameUser;
    private javax.swing.JPanel NavbarMenu;
    private javax.swing.JPanel QuanLiDichVu;
    private javax.swing.JPanel QuanLiPhong;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TonKho;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
